/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.conversor.GUI;

import com.conversor.model.*;
import com.conversor.utils.Utilities;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;

/**
 *
 * @author felip
 */
public class Pantalla extends javax.swing.JFrame {
    
    Double valor;
    Integer opcion;
    String resultado;
    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        this.setContentPane(fondo);
        initComponents();
        pnl_ingresar_valor.setVisible(false);

        //deshabilitar el boton btn_convertir
        btn_convertir.setEnabled(false);
        
        // crear objeto de ConversorLongitudes
        ConversorLongitudes c_longitudes = new ConversorLongitudes(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_conversor = new javax.swing.JLabel();
        pnl_ingresar_valor = new javax.swing.JPanel();
        lbl_opciones = new javax.swing.JLabel();
        lbl_valor = new javax.swing.JLabel();
        btn_convertir = new javax.swing.JButton();
        lbl_valor1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_valor = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_resultado = new javax.swing.JTextPane();
        cb_opciones = new javax.swing.JComboBox<>();
        cb_conversores = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor One");
        setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("CONVERSOR ONE");
        jPanel1.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 6, 416, -1));

        lbl_conversor.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_conversor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_conversor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_conversor.setText("Seleccione un conversor:");
        jPanel1.add(lbl_conversor, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 122, 292, -1));

        pnl_ingresar_valor.setOpaque(false);

        lbl_opciones.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_opciones.setForeground(new java.awt.Color(255, 255, 255));
        lbl_opciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_opciones.setText("Seleccione una opcion:");

        lbl_valor.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_valor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_valor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_valor.setText("Ingrese valor");

        btn_convertir.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_convertir.setText("Convertir");
        btn_convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertirActionPerformed(evt);
            }
        });
        btn_convertir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_convertirKeyReleased(evt);
            }
        });

        lbl_valor1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_valor1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_valor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_valor1.setText("Resultado:");

        txt_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_valorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_valorKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(txt_valor);

        jScrollPane4.setViewportView(txt_resultado);

        cb_opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "" }));
        cb_opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_opcionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ingresar_valorLayout = new javax.swing.GroupLayout(pnl_ingresar_valor);
        pnl_ingresar_valor.setLayout(pnl_ingresar_valorLayout);
        pnl_ingresar_valorLayout.setHorizontalGroup(
            pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresar_valorLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(lbl_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(pnl_ingresar_valorLayout.createSequentialGroup()
                .addGroup(pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ingresar_valorLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(lbl_valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ingresar_valorLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lbl_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ingresar_valorLayout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(btn_convertir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_ingresar_valorLayout.setVerticalGroup(
            pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ingresar_valorLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_opciones)
                    .addComponent(cb_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_valor)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btn_convertir)
                .addGap(31, 31, 31)
                .addGroup(pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresar_valorLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresar_valorLayout.createSequentialGroup()
                        .addComponent(lbl_valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        jPanel1.add(pnl_ingresar_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 185, -1, -1));

        cb_conversores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un conversor", "Longitud", "Monedas", "Temperatura", "Idioma" }));
        cb_conversores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_conversoresActionPerformed(evt);
            }
        });
        jPanel1.add(cb_conversores, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 124, 283, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertirActionPerformed
        
        //mostrar resultado
        txt_resultado.setText(this.resultado);
    }//GEN-LAST:event_btn_convertirActionPerformed

    private void cb_conversoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_conversoresActionPerformed
        //Cuando se seleccione el conversor de longitud se debe mostrar el siguiente mensaje:
        String selected = cb_conversores.getSelectedItem().toString();
        if (selected.equals("Longitud")) {                        
            //obtener opciones del conversor
            String[] opciones = ConversorLongitudes.getOpciones();
            cb_opciones.setModel(new javax.swing.DefaultComboBoxModel<>(opciones));
            
            lbl_valor.setText("Ingrese el valor:");
            pnl_ingresar_valor.setVisible(true);
        }
    }//GEN-LAST:event_cb_conversoresActionPerformed

    private void cb_opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_opcionesActionPerformed
        String selected = cb_opciones.getSelectedItem().toString();
        Integer op = cb_opciones.getSelectedIndex();
        //System.out.println("opciones"+op);
        this.opcion = op;
        
        if(op==1){
            lbl_valor.setText("Ingrese el valor metros:");
        }else{
            lbl_valor.setText("Ingrese el valor en centímetros:");
        }
    }//GEN-LAST:event_cb_opcionesActionPerformed

    private void txt_valorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_valorKeyPressed

    }//GEN-LAST:event_txt_valorKeyPressed

    private void btn_convertirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_convertirKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_convertirKeyReleased

    private void txt_valorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_valorKeyReleased
        String txt = txt_valor.getText();
        //System.out.println("valor: "+Utilities.esNumero(txt)+" ->"+txt);
        
        if(txt!=null && txt!=""){
            if (Utilities.esNumero(txt)) {
                this.valor = Double.valueOf(txt_valor.getText());
                if(valor<0.0){
                    showMessageDialog(null, "El valor debe ser positivo");
                }else{

                    //si opcion esta vacio, mostrar mensaje
                    if(opcion==null){
                        showMessageDialog(null, "Sellecione una opcion");
                    }

                    this.resultado = ConversorLongitudes.convertir(opcion, valor);
                    btn_convertir.setEnabled(true);
                }

            } else {
                showMessageDialog(null, "El texto no es un número.");
            }
        }
    }//GEN-LAST:event_txt_valorKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Pantalla().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_convertir;
    private javax.swing.JComboBox<String> cb_conversores;
    private javax.swing.JComboBox<String> cb_opciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_conversor;
    private javax.swing.JLabel lbl_opciones;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_valor;
    private javax.swing.JLabel lbl_valor1;
    private javax.swing.JPanel pnl_ingresar_valor;
    private javax.swing.JTextPane txt_resultado;
    private javax.swing.JTextPane txt_valor;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel 
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/com/conversor/sources/background.jpg")).getImage();
            
            
//            URL imageUrl = getClass().getResource("/com/conversor/sources/background.jpg");
//            System.out.println("imageURL:"+imageUrl);

            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
}