/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.conversor.GUI;

import com.conversor.model.*;

/**
 *
 * @author felip
 */
public class Pantalla extends javax.swing.JFrame {
    
    Double valor;
    Integer opcion;
    String resultado;

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        pnl_ingresar_valor.setVisible(false);

        //deshabilitar el boton btn_convertir
        btn_convertir.setEnabled(false);
        
        // crear objeto de ConversorLongitudes
        ConversorLongitudes c_longitudes = new ConversorLongitudes(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_conversor = new javax.swing.JLabel();
        cb_conversores = new javax.swing.JComboBox<>();
        pnl_ingresar_valor = new javax.swing.JPanel();
        lbl_opciones = new javax.swing.JLabel();
        cb_opciones = new javax.swing.JComboBox<>();
        lbl_valor = new javax.swing.JLabel();
        btn_convertir = new javax.swing.JButton();
        lbl_valor1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_valor = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_resultado = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor One");

        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("CONVERSOR ONE");

        lbl_conversor.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_conversor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_conversor.setText("Seleccione un conversor:");

        cb_conversores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un conversor", "Longitud", "Monedas", "Temperatura", "Idioma" }));
        cb_conversores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_conversoresActionPerformed(evt);
            }
        });

        lbl_opciones.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_opciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_opciones.setText("Seleccione un conversor:");

        cb_opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un conversor", " " }));
        cb_opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_opcionesActionPerformed(evt);
            }
        });

        lbl_valor.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_valor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_valor.setText("Ingrese valor");

        btn_convertir.setText("Convertir");
        btn_convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertirActionPerformed(evt);
            }
        });

        lbl_valor1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_valor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_valor1.setText("Resultado:");

        txt_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_valorKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(txt_valor);

        jScrollPane4.setViewportView(txt_resultado);

        javax.swing.GroupLayout pnl_ingresar_valorLayout = new javax.swing.GroupLayout(pnl_ingresar_valor);
        pnl_ingresar_valor.setLayout(pnl_ingresar_valorLayout);
        pnl_ingresar_valorLayout.setHorizontalGroup(
            pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ingresar_valorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresar_valorLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_convertir)
                            .addGap(241, 241, 241))
                        .addGroup(pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_ingresar_valorLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(lbl_valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_ingresar_valorLayout.createSequentialGroup()
                                .addComponent(lbl_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))))
                    .addGroup(pnl_ingresar_valorLayout.createSequentialGroup()
                        .addComponent(lbl_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(cb_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        pnl_ingresar_valorLayout.setVerticalGroup(
            pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ingresar_valorLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_opciones)
                    .addComponent(cb_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_valor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_convertir)
                .addGroup(pnl_ingresar_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_valor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(lbl_conversor, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(cb_conversores, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_ingresar_valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_conversores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_conversor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_ingresar_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertirActionPerformed
        // convertir 
        this.valor = Double.valueOf(txt_valor.getText());
        this.resultado = ConversorLongitudes.convertir(opcion, valor);
        
        //mostrar resultado
        txt_resultado.setText(this.resultado);
    }//GEN-LAST:event_btn_convertirActionPerformed

    private void cb_conversoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_conversoresActionPerformed
        //Cuando se seleccione el conversor de longitud se debe mostrar el siguiente mensaje:
        String selected = cb_conversores.getSelectedItem().toString();
        if (selected.equals("Longitud")) {
                        
            //obtener opciones del conversor
            String[] opciones = ConversorLongitudes.getOpciones();
            cb_opciones.setModel(new javax.swing.DefaultComboBoxModel<>(opciones));
            
            lbl_valor.setText("Ingrese el valor:");
            pnl_ingresar_valor.setVisible(true);
        }
    }//GEN-LAST:event_cb_conversoresActionPerformed

    private void cb_opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_opcionesActionPerformed
        String selected = cb_opciones.getSelectedItem().toString();
        Integer op = cb_opciones.getSelectedIndex();
        //System.out.println("opciones"+op);
        this.opcion = op;
    }//GEN-LAST:event_cb_opcionesActionPerformed

    private void txt_valorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_valorKeyPressed
        // TODO add your handling code here:
        btn_convertir.setEnabled(true);
    }//GEN-LAST:event_txt_valorKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Pantalla().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_convertir;
    private javax.swing.JComboBox<String> cb_conversores;
    private javax.swing.JComboBox<String> cb_opciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_conversor;
    private javax.swing.JLabel lbl_opciones;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_valor;
    private javax.swing.JLabel lbl_valor1;
    private javax.swing.JPanel pnl_ingresar_valor;
    private javax.swing.JTextPane txt_resultado;
    private javax.swing.JTextPane txt_valor;
    // End of variables declaration//GEN-END:variables
}
