/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.conversor.GUI;

import com.conversor.model.*;
import com.conversor.utils.Utilities;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;

/**
 *
 * @author felip
 */
public class Pantalla1 extends javax.swing.JFrame {
    
    String conversor;
    Double valor;
    String LONGITUD1, LONGITUD2;
    String resultado;
    String MONEDA1, MONEDA2;
    Double valor1, valor2;
    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form Pantalla
     */
    public Pantalla1() {
        this.setContentPane(fondo);
        initComponents();
        pnl_ingresar_valor.setVisible(false);

        
        // crear objeto de ConversorLongitudes
        ConversorLongitudes c_longitudes = new ConversorLongitudes(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_conversor = new javax.swing.JLabel();
        cb_conversores = new javax.swing.JComboBox<>();
        pnl_ingresar_valor = new javax.swing.JPanel();
        lbl_opciones = new javax.swing.JLabel();
        cb_opciones1 = new javax.swing.JComboBox<>();
        cb_opciones2 = new javax.swing.JComboBox<>();
        txt_valor1 = new javax.swing.JTextPane();
        txt_valor2 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor One");
        setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("CONVERSOR ONE");
        jPanel1.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 6, 416, -1));

        lbl_conversor.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_conversor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_conversor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_conversor.setText("Seleccione un conversor:");
        jPanel1.add(lbl_conversor, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 122, 292, -1));

        cb_conversores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un conversor", "Longitud", "Monedas", "Temperatura", "Idioma" }));
        cb_conversores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_conversoresActionPerformed(evt);
            }
        });
        jPanel1.add(cb_conversores, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 124, 283, -1));

        pnl_ingresar_valor.setOpaque(false);
        pnl_ingresar_valor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_opciones.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_opciones.setForeground(new java.awt.Color(255, 255, 255));
        lbl_opciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_opciones.setText("Seleccione una opcion:");
        pnl_ingresar_valor.add(lbl_opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 292, -1));

        cb_opciones1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "" }));
        cb_opciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_opciones1ActionPerformed(evt);
            }
        });
        pnl_ingresar_valor.add(cb_opciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 130, -1));

        cb_opciones2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "" }));
        cb_opciones2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_opciones2ActionPerformed(evt);
            }
        });
        pnl_ingresar_valor.add(cb_opciones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 130, -1));

        txt_valor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_valor1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_valor1KeyReleased(evt);
            }
        });
        pnl_ingresar_valor.add(txt_valor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 150, 30));

        txt_valor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_valor2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_valor2KeyReleased(evt);
            }
        });
        pnl_ingresar_valor.add(txt_valor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 150, 30));

        jPanel1.add(pnl_ingresar_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 185, 840, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_conversoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_conversoresActionPerformed
        //Cuando se seleccione el conversor de longitud se debe mostrar el siguiente mensaje:
        this.conversor = cb_conversores.getSelectedItem().toString();
        String[] opciones = new String[] { "Seleccione una opcion", "" };
        if (conversor.equals("Longitud")) {                        
            //obtener opciones del conversor
            opciones = ConversorLongitudes.getOpciones();
        } else if(conversor.equals("Monedas")){
            //obtener opciones del conversor
            opciones = ConversorMonedas.getOpciones();
        }
        cb_opciones1.setModel(new javax.swing.DefaultComboBoxModel<>(opciones));            
        cb_opciones2.setModel(new javax.swing.DefaultComboBoxModel<>(opciones));
        pnl_ingresar_valor.setVisible(true);
    }//GEN-LAST:event_cb_conversoresActionPerformed

    private void cb_opciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_opciones1ActionPerformed
        String selected = cb_opciones1.getSelectedItem().toString();
        //Integer op = cb_opciones1.getSelectedIndex();
        //System.out.println("opciones1: "+op + " ->"+selected);   
        if(this.conversor=="Longitud"){
            this.LONGITUD1 = selected;
        }else if(this.conversor=="Monedas"){
            this.MONEDA1 = selected;
        }
    }//GEN-LAST:event_cb_opciones1ActionPerformed

    private void cb_opciones2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_opciones2ActionPerformed
        // TODO add your handling code here:
        String selected = cb_opciones2.getSelectedItem().toString();
        //Integer op = cb_opciones2.getSelectedIndex();
        //System.out.println("opciones1: "+op + " ->"+selected);       
        if(this.conversor=="Longitud"){
            this.LONGITUD2 = selected;
        }else if(this.conversor=="Monedas"){
            this.MONEDA2 = selected;
        }
    }//GEN-LAST:event_cb_opciones2ActionPerformed

    private void txt_valor1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_valor1KeyReleased
        // TODO add your handling code here:
        String txt = txt_valor1.getText();
        try{
            if(txt!=null && txt!=""){
                Double valorUsuario = Double.valueOf(txt);
                this.valor1 = valorUsuario;                
                
                if(this.conversor=="Longitud"){
                    convertirLongitud1();
                }else if(this.conversor=="Monedas"){
                    convertirMoneda1();
                }
            }
        }catch(Exception e){
            showMessageDialog(null, "VALOR INCORRECTO");
        }
    }//GEN-LAST:event_txt_valor1KeyReleased

    private void txt_valor2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_valor2KeyReleased
        String txt = txt_valor2.getText();
        //System.out.println("valor: "+Utilities.esNumero(txt)+" ->"+txt);
        
        if(txt!=null && txt!=""){
            if (Utilities.esNumero(txt)) {      
                this.valor2 = Double.valueOf(txt_valor2.getText());  
                if(valor2<0.0){
                    showMessageDialog(null, "El valor debe ser positivo");
                }else{
                    //si opcion esta vacio, mostrar mensaje
                    if(this.conversor=="Longitud"){
                        convertirLongitud2();
                    }else if(this.conversor=="Monedas"){
                        convertirMoneda2();
                    }
                }
            } else {
                showMessageDialog(null, "El texto no es un número.");
            }
        }
    }//GEN-LAST:event_txt_valor2KeyReleased

    private void txt_valor1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_valor1KeyPressed
        
    }//GEN-LAST:event_txt_valor1KeyPressed
    
    private void txt_valor2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_valor2KeyPressed
        
    }//GEN-LAST:event_txt_valor2KeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Pantalla().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_conversores;
    private javax.swing.JComboBox<String> cb_opciones1;
    private javax.swing.JComboBox<String> cb_opciones2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_conversor;
    private javax.swing.JLabel lbl_opciones;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel pnl_ingresar_valor;
    private javax.swing.JTextPane txt_valor1;
    private javax.swing.JTextPane txt_valor2;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel 
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/com/conversor/sources/background.jpg")).getImage();
                        
            //URL imageUrl = getClass().getResource("/com/conversor/sources/background.jpg");
            //System.out.println("imageURL:"+imageUrl);
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
    
    private void convertirMoneda1() {
        if (this.MONEDA1 == null && this.MONEDA1.length() > 3 || this.MONEDA2 == null && this.MONEDA2.length() > 3) {
            showMessageDialog(null, "Seleccione una opcion");
        } else {
            String resultado = ConversorMonedas.convertir(this.MONEDA1, this.MONEDA2, valor1);
            txt_valor2.setText(resultado);
        }
    }
    private void convertirMoneda2() {
        if (this.MONEDA1 == null && this.MONEDA1.length() > 3 || this.MONEDA2 == null && this.MONEDA2.length() > 3) {
            showMessageDialog(null, "Seleccione una opcion");
        } else {
            String resultado = ConversorMonedas.convertir(this.MONEDA2, this.MONEDA1, valor2);
            txt_valor1.setText(resultado);
        }
    }

    private void convertirLongitud1() {
        if (this.LONGITUD1 == null && this.LONGITUD1.length() > 3 || this.LONGITUD2 == null && this.LONGITUD2.length() > 3) {
            showMessageDialog(null, "Seleccione una opcion");
        } else {
            String resultado = ConversorLongitudes.convertir(this.LONGITUD1, this.LONGITUD2, valor1);
            txt_valor2.setText(resultado);
        }
    }
    private void convertirLongitud2() {
        if (this.LONGITUD1 == null && this.LONGITUD1.length() > 3 || this.LONGITUD2 == null && this.LONGITUD2.length() > 3) {
            showMessageDialog(null, "Seleccione una opcion");
        } else {
            String resultado = ConversorLongitudes.convertir(this.LONGITUD2, this.LONGITUD1, valor2);
            txt_valor1.setText(resultado);
        }
    }
}